nodeLinker: pnp

yarnPath: .yarn/releases/yarn-3.2.2.cjs

packageExtensions:
  "@yarnpkg/esbuild-plugin-pnp@*":
    dependencies:
      supports-color: "*"
  "@swc/cli@*":
    dependencies:
      chokidar: "*"
  "@n1ru4l/graphql-live-query@*":
    dependencies:
      tslib: "*"
  "@envelop/core@*":
    dependencies:
      tslib: "*"
  "@envelop/types@*":
    dependencies:
      tslib: "*"
